// فبركة | Fabrication's starter question bank.
//
// Every row is one outrageous-but-true fact with a single short answer --
// short on purpose, because the whole game is other players inventing answers
// that could sit beside it without looking wrong. A question whose real answer
// is a sentence cannot be faked convincingly, and a question whose answer is
// guessable from the wording is not worth asking.
//
// Arabic is written as Arabic gameplay text rather than translated from the
// English line, per the spec's requirement that the two languages stand alone.
//
// `source` names where the fact is verifiable. These were written from
// reference knowledge and have NOT been checked against the sources listed --
// they need a fact-checking pass before this bank goes in front of players,
// and `sourceUrl` is deliberately left empty rather than filled with links
// that were never opened.
export interface FabricationSeedQuestion {
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
  prompt: string;
  promptAr: string;
  answer: string;
  answerAr: string;
  acceptedVariants?: string[];
  acceptedVariantsAr?: string[];
  source: string;
}

export const FABRICATION_QUESTIONS: FabricationSeedQuestion[] = [
  // --- Animals ---
  {
    category: 'Animals',
    difficulty: 'easy',
    prompt: 'An octopus has three of these organs. Which organ?',
    promptAr: 'يمتلك الأخطبوط ثلاثة من هذا العضو. ما هو؟',
    answer: 'Hearts',
    answerAr: 'قلوب',
    acceptedVariants: ['heart'],
    acceptedVariantsAr: ['قلب', 'القلب'],
    source: 'Encyclopaedia Britannica — Octopus',
  },
  {
    category: 'Animals',
    difficulty: 'medium',
    prompt: 'A group of flamingos is called a what?',
    promptAr: 'ماذا تُسمّى مجموعة طيور الفلامنغو؟',
    answer: 'Flamboyance',
    answerAr: 'فلامبوينس',
    source: 'Oxford English Dictionary — collective nouns',
  },
  {
    category: 'Animals',
    difficulty: 'medium',
    prompt: 'Wombat droppings are famous for being what shape?',
    promptAr: 'تشتهر فضلات حيوان الومبت بأنها على شكل ماذا؟',
    answer: 'Cubes',
    answerAr: 'مكعبات',
    acceptedVariants: ['cube', 'square'],
    acceptedVariantsAr: ['مكعب', 'مربع'],
    source: 'Georgia Tech / University of Tasmania research, 2018',
  },
  {
    category: 'Animals',
    difficulty: 'medium',
    prompt: 'It is the only bird that can fly backwards. Which bird?',
    promptAr: 'هو الطائر الوحيد القادر على الطيران إلى الخلف. ما هو؟',
    answer: 'Hummingbird',
    answerAr: 'الطائر الطنان',
    acceptedVariantsAr: ['طائر طنان', 'الطنان'],
    source: 'Cornell Lab of Ornithology',
  },
  {
    category: 'Animals',
    difficulty: 'hard',
    prompt: "A shrimp's heart is located in which part of its body?",
    promptAr: 'في أي جزء من جسم الروبيان يقع قلبه؟',
    answer: 'Its head',
    answerAr: 'في رأسه',
    acceptedVariants: ['head', 'the head'],
    acceptedVariantsAr: ['الرأس', 'رأسه'],
    source: 'NOAA Fisheries',
  },
  {
    category: 'Animals',
    difficulty: 'easy',
    prompt: 'Sea otters hold hands while they sleep to stop themselves doing what?',
    promptAr: 'يمسك قضاعة البحر بأيدي بعضها أثناء النوم لتمنع نفسها من فعل ماذا؟',
    answer: 'Drifting apart',
    answerAr: 'الانجراف بعيدًا',
    acceptedVariants: ['drifting away', 'floating away', 'drifting'],
    acceptedVariantsAr: ['الانجراف', 'الابتعاد'],
    source: 'Monterey Bay Aquarium',
  },
  {
    category: 'Animals',
    difficulty: 'medium',
    prompt: 'Honeybees tell each other where food is by performing which dance?',
    promptAr: 'يخبر نحل العسل بعضه بموقع الطعام عن طريق أداء أي رقصة؟',
    answer: 'The waggle dance',
    answerAr: 'رقصة الاهتزاز',
    acceptedVariants: ['waggle', 'waggle dance'],
    acceptedVariantsAr: ['الاهتزاز', 'رقصة الهز'],
    source: 'Karl von Frisch, Nobel Prize in Physiology or Medicine 1973',
  },
  {
    category: 'Animals',
    difficulty: 'medium',
    prompt: 'A group of crows is known by which grim collective noun?',
    promptAr: 'تُعرف مجموعة الغربان باسم جماعي مخيف. ما هو؟',
    answer: 'A murder',
    answerAr: 'جريمة قتل',
    acceptedVariants: ['murder'],
    acceptedVariantsAr: ['جريمة', 'مقتلة'],
    source: 'Oxford English Dictionary — collective nouns',
  },
  {
    category: 'Animals',
    difficulty: 'hard',
    prompt: 'Because of the way their tails and legs work, kangaroos cannot do what?',
    promptAr: 'بسبب طريقة عمل ذيلها وساقيها، لا تستطيع الكناغر فعل ماذا؟',
    answer: 'Walk backwards',
    answerAr: 'المشي إلى الخلف',
    acceptedVariants: ['move backwards', 'go backwards', 'walk back'],
    acceptedVariantsAr: ['المشي للخلف', 'السير إلى الوراء'],
    source: 'Australian Museum',
  },
  {
    category: 'Animals',
    difficulty: 'easy',
    prompt: "A blue whale's tongue alone can weigh about as much as which animal?",
    promptAr: 'يمكن أن يزن لسان الحوت الأزرق وحده مثل أي حيوان تقريبًا؟',
    answer: 'An elephant',
    answerAr: 'فيل',
    acceptedVariants: ['elephant'],
    acceptedVariantsAr: ['الفيل'],
    source: 'World Wildlife Fund',
  },

  // --- History ---
  {
    category: 'History',
    difficulty: 'hard',
    prompt: 'The shortest war in recorded history lasted roughly how many minutes?',
    promptAr: 'استمرت أقصر حرب في التاريخ المسجل نحو كم دقيقة؟',
    answer: '38 minutes',
    answerAr: '٣٨ دقيقة',
    acceptedVariants: ['38', 'thirty-eight', 'thirty eight minutes'],
    acceptedVariantsAr: ['38', '38 دقيقة', 'ثمان وثلاثون دقيقة'],
    source: 'Guinness World Records — Anglo-Zanzibar War, 1896',
  },
  {
    category: 'History',
    difficulty: 'hard',
    prompt: 'Oxford University was already teaching students when which empire was founded?',
    promptAr: 'كانت جامعة أكسفورد تُدرّس طلابها بالفعل عندما تأسست أي إمبراطورية؟',
    answer: 'The Aztec Empire',
    answerAr: 'إمبراطورية الأزتك',
    acceptedVariants: ['aztec', 'aztec empire', 'the aztecs'],
    acceptedVariantsAr: ['الأزتك', 'الأزتيك'],
    source: 'University of Oxford historical record; Britannica — Aztec',
  },
  {
    category: 'History',
    difficulty: 'hard',
    prompt: 'Cleopatra lived closer in time to the Moon landing than to the building of what?',
    promptAr: 'عاشت كليوباترا زمنيًا أقرب إلى الهبوط على القمر منها إلى بناء ماذا؟',
    answer: 'The Great Pyramid of Giza',
    answerAr: 'الهرم الأكبر في الجيزة',
    acceptedVariants: ['the great pyramid', 'great pyramid', 'the pyramids', 'pyramids of giza'],
    acceptedVariantsAr: ['الهرم الأكبر', 'أهرامات الجيزة', 'الأهرامات'],
    source: 'Britannica — Cleopatra; Great Pyramid of Giza construction dates',
  },
  {
    category: 'History',
    difficulty: 'medium',
    prompt: 'In 1807, Napoleon was famously forced to flee from a swarm of which animals?',
    promptAr: 'في عام ١٨٠٧، اضطر نابليون للفرار من سرب من أي حيوانات؟',
    answer: 'Rabbits',
    answerAr: 'أرانب',
    acceptedVariants: ['rabbit', 'bunnies'],
    acceptedVariantsAr: ['الأرانب', 'أرنب'],
    source: 'Recorded by Napoleon’s chief of staff Berthier; History Today',
  },
  {
    category: 'History',
    difficulty: 'medium',
    prompt: 'In 1962 an outbreak in Tanganyika closed schools for months. An outbreak of what?',
    promptAr: 'في عام ١٩٦٢ أغلق وباء في تنجانيقا المدارس لأشهر. وباء ماذا؟',
    answer: 'Laughter',
    answerAr: 'الضحك',
    acceptedVariants: ['laughing', 'contagious laughter'],
    acceptedVariantsAr: ['ضحك', 'نوبات ضحك'],
    source: 'Central African Journal of Medicine, 1963',
  },
  {
    category: 'History',
    difficulty: 'medium',
    prompt: 'Ancient Romans used this bodily fluid as a mouthwash. Which one?',
    promptAr: 'استخدم الرومان القدماء هذا السائل الجسدي كغسول للفم. ما هو؟',
    answer: 'Urine',
    answerAr: 'البول',
    acceptedVariants: ['pee', 'human urine'],
    acceptedVariantsAr: ['بول'],
    source: 'Catullus, Poem 39; Smithsonian Magazine',
  },
  {
    category: 'History',
    difficulty: 'hard',
    prompt: 'The very first item ever sold on eBay was a broken what?',
    promptAr: 'أول سلعة بيعت على الإطلاق في موقع إيباي كانت شيئًا معطلاً. ما هو؟',
    answer: 'A laser pointer',
    answerAr: 'مؤشر ليزر',
    acceptedVariants: ['laser pointer', 'broken laser pointer'],
    acceptedVariantsAr: ['مؤشر ليزر معطل', 'قلم ليزر'],
    source: 'eBay company history; Pierre Omidyar interviews',
  },
  {
    category: 'History',
    difficulty: 'hard',
    prompt: 'The Great Fire of London destroyed most of the city, but its official death toll was how many?',
    promptAr: 'دمّر حريق لندن الكبير معظم المدينة، لكن العدد الرسمي للوفيات كان كم؟',
    answer: 'Six',
    answerAr: 'ستة',
    acceptedVariants: ['6', 'six people'],
    acceptedVariantsAr: ['٦', '6', 'ست'],
    source: 'Museum of London — Great Fire of 1666',
  },

  // --- Science ---
  {
    category: 'Science',
    difficulty: 'hard',
    prompt: 'Under the right conditions hot water can freeze faster than cold water. What is this effect called?',
    promptAr: 'في ظروف معينة يتجمد الماء الساخن أسرع من البارد. ماذا تُسمّى هذه الظاهرة؟',
    answer: 'The Mpemba effect',
    answerAr: 'ظاهرة ممبيمبا',
    acceptedVariants: ['mpemba', 'mpemba effect'],
    acceptedVariantsAr: ['ممبيمبا', 'أثر ممبيمبا'],
    source: 'Physics Education, Mpemba & Osborne, 1969',
  },
  {
    category: 'Science',
    difficulty: 'medium',
    prompt: 'Because of the potassium they contain, bananas are very slightly what?',
    promptAr: 'بسبب البوتاسيوم الذي تحتويه، يكون الموز بدرجة طفيفة جدًا ماذا؟',
    answer: 'Radioactive',
    answerAr: 'مشعًّا',
    acceptedVariants: ['radioactive'],
    acceptedVariantsAr: ['مشع', 'إشعاعي'],
    source: 'US Environmental Protection Agency — potassium-40',
  },
  {
    category: 'Science',
    difficulty: 'hard',
    prompt: 'Helium was discovered somewhere else before it was ever found on Earth. Where?',
    promptAr: 'اكتُشف عنصر الهيليوم في مكان آخر قبل أن يُعثر عليه على الأرض. أين؟',
    answer: 'The Sun',
    answerAr: 'الشمس',
    acceptedVariants: ['sun', 'in the sun', 'the suns spectrum'],
    acceptedVariantsAr: ['في الشمس', 'طيف الشمس'],
    source: 'Royal Society — Janssen and Lockyer, 1868',
  },
  {
    category: 'Science',
    difficulty: 'medium',
    prompt: 'At one specific temperature and pressure, water boils and freezes at the same time. What is that point called?',
    promptAr: 'عند درجة حرارة وضغط محددين، يغلي الماء ويتجمد في آن واحد. ماذا تُسمّى هذه النقطة؟',
    answer: 'The triple point',
    answerAr: 'النقطة الثلاثية',
    acceptedVariants: ['triple point'],
    acceptedVariantsAr: ['نقطة ثلاثية'],
    source: 'International Union of Pure and Applied Chemistry',
  },
  {
    category: 'Science',
    difficulty: 'hard',
    prompt: "A bolt of lightning is roughly how many times hotter than the Sun's surface?",
    promptAr: 'صاعقة البرق أسخن من سطح الشمس بنحو كم مرة؟',
    answer: 'About five times',
    answerAr: 'نحو خمس مرات',
    acceptedVariants: ['five', '5', 'five times', '5 times'],
    acceptedVariantsAr: ['خمس مرات', '5', '٥'],
    source: 'US National Weather Service',
  },

  // --- Geography ---
  {
    category: 'Geography',
    difficulty: 'medium',
    prompt: 'Russia is so wide that it spans how many time zones?',
    promptAr: 'روسيا شاسعة لدرجة أنها تمتد عبر كم منطقة زمنية؟',
    answer: 'Eleven',
    answerAr: 'إحدى عشرة',
    acceptedVariants: ['11', 'eleven time zones'],
    acceptedVariantsAr: ['١١', '11', 'احدى عشرة'],
    source: 'CIA World Factbook — Russia',
  },
  {
    category: 'Geography',
    difficulty: 'hard',
    prompt: 'Which country has more pyramids than Egypt?',
    promptAr: 'أي دولة تضم أهرامات أكثر من مصر؟',
    answer: 'Sudan',
    answerAr: 'السودان',
    acceptedVariantsAr: ['سودان'],
    source: 'UNESCO — Meroe, Nubian pyramids',
  },
  {
    category: 'Geography',
    difficulty: 'hard',
    prompt: 'Africa is the only continent that sits in all four of these. All four what?',
    promptAr: 'أفريقيا هي القارة الوحيدة التي تقع في جميع هذه الأربعة. أربعة ماذا؟',
    answer: 'Hemispheres',
    answerAr: 'أنصاف الكرة الأرضية',
    acceptedVariants: ['hemisphere', 'the hemispheres'],
    acceptedVariantsAr: ['نصف الكرة', 'الأنصاف'],
    source: 'National Geographic — Africa',
  },
  {
    category: 'Geography',
    difficulty: 'medium',
    prompt: 'Canada has more of these than the rest of the world combined. More of what?',
    promptAr: 'تمتلك كندا من هذه أكثر من بقية العالم مجتمعًا. أكثر من ماذا؟',
    answer: 'Lakes',
    answerAr: 'البحيرات',
    acceptedVariants: ['lake'],
    acceptedVariantsAr: ['بحيرات', 'بحيرة'],
    source: 'Natural Resources Canada',
  },
  {
    category: 'Geography',
    difficulty: 'medium',
    prompt: 'Istanbul is the only major city in the world that sits on two of these. Two what?',
    promptAr: 'إسطنبول هي المدينة الكبرى الوحيدة في العالم التي تقع على اثنين من هذه. اثنين من ماذا؟',
    answer: 'Continents',
    answerAr: 'قارات',
    acceptedVariants: ['continent'],
    acceptedVariantsAr: ['القارات', 'قارتين'],
    source: 'Britannica — Istanbul',
  },
  {
    category: 'Geography',
    difficulty: 'hard',
    prompt: 'Which country flies the only national flag in the world that is not a rectangle?',
    promptAr: 'أي دولة ترفع العلم الوطني الوحيد في العالم الذي ليس مستطيلاً؟',
    answer: 'Nepal',
    answerAr: 'نيبال',
    source: 'Constitution of Nepal, Schedule 1',
  },

  // --- Food ---
  {
    category: 'Food',
    difficulty: 'medium',
    prompt: 'Archaeologists found pots of this still edible in Egyptian tombs. Pots of what?',
    promptAr: 'عثر علماء الآثار على أوانٍ من هذا لا تزال صالحة للأكل في مقابر مصرية. أوانٍ من ماذا؟',
    answer: 'Honey',
    answerAr: 'عسل',
    acceptedVariantsAr: ['العسل'],
    source: 'Smithsonian Magazine; National Geographic',
  },
  {
    category: 'Food',
    difficulty: 'medium',
    prompt: 'Before the 17th century, almost all cultivated carrots were which colour?',
    promptAr: 'قبل القرن السابع عشر، كان معظم الجزر المزروع بأي لون؟',
    answer: 'Purple',
    answerAr: 'بنفسجي',
    acceptedVariants: ['violet'],
    acceptedVariantsAr: ['أرجواني', 'البنفسجي'],
    source: 'World Carrot Museum; Journal of Agricultural History',
  },
  {
    category: 'Food',
    difficulty: 'hard',
    prompt: 'In the 1830s, ketchup was sold in America as a what?',
    promptAr: 'في ثلاثينيات القرن التاسع عشر، بيع الكاتشب في أمريكا على أنه ماذا؟',
    answer: 'Medicine',
    answerAr: 'دواء',
    acceptedVariants: ['a medicine', 'cure', 'tomato pills'],
    acceptedVariantsAr: ['الدواء', 'علاج'],
    source: 'Smithsonian Magazine — Dr John Cook Bennett, 1834',
  },
  {
    category: 'Food',
    difficulty: 'easy',
    prompt: 'The pineapple got its English name because early Europeans thought it looked like what?',
    promptAr: 'حصل الأناناس على اسمه الإنجليزي لأن الأوروبيين الأوائل ظنوا أنه يشبه ماذا؟',
    answer: 'A pine cone',
    answerAr: 'كوز الصنوبر',
    acceptedVariants: ['pine cone', 'pinecone'],
    acceptedVariantsAr: ['كوز صنوبر', 'ثمرة الصنوبر'],
    source: 'Oxford English Dictionary — pineapple, etymology',
  },
  {
    category: 'Food',
    difficulty: 'hard',
    prompt: 'Studies repeatedly name it the most shoplifted food in the world. Which food?',
    promptAr: 'تشير الدراسات مرارًا إلى أنه الطعام الأكثر سرقة من المتاجر في العالم. ما هو؟',
    answer: 'Cheese',
    answerAr: 'الجبن',
    acceptedVariantsAr: ['جبن', 'الجبنة'],
    source: 'Global Retail Theft Barometer',
  },

  // --- Human body ---
  {
    category: 'Human body',
    difficulty: 'medium',
    prompt: 'A baby is born with roughly how many bones — far more than an adult has?',
    promptAr: 'يولد الطفل بنحو كم عظمة، وهو عدد يفوق بكثير ما لدى البالغ؟',
    answer: 'About 300',
    answerAr: 'نحو ٣٠٠',
    acceptedVariants: ['300', 'three hundred'],
    acceptedVariantsAr: ['300', '٣٠٠', 'ثلاثمئة'],
    source: 'Cleveland Clinic; Nemours KidsHealth',
  },
  {
    category: 'Human body',
    difficulty: 'easy',
    prompt: 'Try it: you cannot hum while holding which part of your body closed?',
    promptAr: 'جرّبها: لا يمكنك الدندنة وأنت تغلق أي جزء من جسمك؟',
    answer: 'Your nose',
    answerAr: 'أنفك',
    acceptedVariants: ['nose', 'the nose', 'nostrils'],
    acceptedVariantsAr: ['الأنف', 'أنف'],
    source: 'Basic physiology of phonation — humming requires nasal airflow',
  },
  {
    category: 'Human body',
    difficulty: 'hard',
    prompt: 'A 2014 study in Science concluded the human nose can distinguish roughly how many smells?',
    promptAr: 'خلصت دراسة نُشرت في مجلة ساينس عام ٢٠١٤ إلى أن أنف الإنسان يميز نحو كم رائحة؟',
    answer: 'A trillion',
    answerAr: 'تريليون',
    acceptedVariants: ['one trillion', 'trillion', '1 trillion'],
    acceptedVariantsAr: ['تريليون رائحة', 'ترليون'],
    source: 'Bushdid et al., Science, 2014',
  },
  {
    category: 'Human body',
    difficulty: 'hard',
    prompt: 'Pound for pound, which muscle is usually called the strongest in the human body?',
    promptAr: 'بالنسبة إلى وزنها، أي عضلة تُوصف عادةً بأنها الأقوى في جسم الإنسان؟',
    answer: 'The masseter, the jaw muscle',
    answerAr: 'العضلة الماضغة في الفك',
    acceptedVariants: ['masseter', 'jaw muscle', 'the jaw'],
    acceptedVariantsAr: ['الماضغة', 'عضلة الفك', 'الفك'],
    source: 'Guinness World Records — strongest muscle',
  },

  // --- Inventions ---
  {
    category: 'Inventions',
    difficulty: 'medium',
    prompt: 'Bubble wrap was originally invented and sold as what?',
    promptAr: 'اختُرع غلاف الفقاعات في الأصل وبيع على أنه ماذا؟',
    answer: 'Wallpaper',
    answerAr: 'ورق جدران',
    acceptedVariants: ['textured wallpaper', 'wall paper'],
    acceptedVariantsAr: ['ورق حائط', 'ورق الجدران'],
    source: 'Sealed Air company history, 1957',
  },
  {
    category: 'Inventions',
    difficulty: 'medium',
    prompt: 'The microwave oven was invented after an engineer noticed what had melted in his pocket?',
    promptAr: 'اختُرع فرن الميكروويف بعد أن لاحظ مهندس أن شيئًا ذاب في جيبه. ما هو؟',
    answer: 'A chocolate bar',
    answerAr: 'لوح شوكولاتة',
    acceptedVariants: ['chocolate', 'chocolate bar', 'a candy bar'],
    acceptedVariantsAr: ['شوكولاتة', 'قطعة شوكولاتة'],
    source: 'Raytheon company history — Percy Spencer, 1945',
  },
  {
    category: 'Inventions',
    difficulty: 'hard',
    prompt: 'Play-Doh was sold for years as a cleaning product for what?',
    promptAr: 'بيع معجون اللعب لسنوات كمنتج تنظيف لماذا؟',
    answer: 'Wallpaper',
    answerAr: 'ورق الجدران',
    acceptedVariants: ['wall paper', 'soot on wallpaper'],
    acceptedVariantsAr: ['ورق حائط', 'ورق جدران'],
    source: 'Smithsonian Magazine — Kutol Products',
  },
  {
    category: 'Inventions',
    difficulty: 'medium',
    prompt: 'The first recorded computer "bug" was literally what?',
    promptAr: 'أول "علة" حاسوبية مسجلة كانت حرفيًا ماذا؟',
    answer: 'A moth',
    answerAr: 'عثّة',
    acceptedVariants: ['moth', 'a dead moth'],
    acceptedVariantsAr: ['فراشة ليلية', 'عثة'],
    source: 'Smithsonian National Museum of American History — Harvard Mark II log, 1947',
  },
  {
    category: 'Inventions',
    difficulty: 'medium',
    prompt: 'Velcro was invented after its creator studied what stuck to his dog?',
    promptAr: 'اختُرع الفيلكرو بعد أن درس مبتكره شيئًا علق بكلبه. ما هو؟',
    answer: 'Burrs',
    answerAr: 'أشواك النباتات',
    acceptedVariants: ['burr', 'burdock burrs', 'seeds'],
    acceptedVariantsAr: ['شوك', 'بذور شائكة', 'الأشواك'],
    source: 'Velcro Companies history — George de Mestral, 1941',
  },

  // --- Culture ---
  {
    category: 'Culture',
    difficulty: 'medium',
    prompt: 'Look closely at the Mona Lisa: she is missing what?',
    promptAr: 'انظر عن قرب إلى لوحة الموناليزا: ما الشيء الغائب عنها؟',
    answer: 'Eyebrows',
    answerAr: 'الحواجب',
    acceptedVariants: ['her eyebrows', 'eyebrows and eyelashes'],
    acceptedVariantsAr: ['حواجب', 'حواجبها'],
    source: 'Musée du Louvre',
  },
  {
    category: 'Culture',
    difficulty: 'hard',
    prompt: 'Before it was called Google, the search engine had which name?',
    promptAr: 'قبل أن يُسمى جوجل، كان لمحرك البحث اسم آخر. ما هو؟',
    answer: 'BackRub',
    answerAr: 'باك راب',
    acceptedVariants: ['back rub'],
    acceptedVariantsAr: ['باكراب'],
    source: 'Stanford University — Page and Brin, 1996',
  },
  {
    category: 'Culture',
    difficulty: 'hard',
    prompt: 'Nintendo was founded in 1889. What did it make?',
    promptAr: 'تأسست نينتندو عام ١٨٨٩. ماذا كانت تصنع؟',
    answer: 'Playing cards',
    answerAr: 'أوراق اللعب',
    acceptedVariants: ['cards', 'hanafuda cards', 'playing card'],
    acceptedVariantsAr: ['ورق لعب', 'كروت لعب', 'بطاقات لعب'],
    source: 'Nintendo corporate history',
  },
  {
    category: 'Culture',
    difficulty: 'medium',
    prompt: 'The Statue of Liberty was which colour when it was unveiled in 1886?',
    promptAr: 'بأي لون كان تمثال الحرية عند إزاحة الستار عنه عام ١٨٨٦؟',
    answer: 'Brown',
    answerAr: 'بني',
    acceptedVariants: ['copper brown', 'copper coloured', 'copper'],
    acceptedVariantsAr: ['نحاسي', 'بني نحاسي', 'اللون البني'],
    source: 'US National Park Service — Statue of Liberty',
  },

  // --- Nature ---
  {
    category: 'Nature',
    difficulty: 'hard',
    prompt: 'Some species of bamboo can grow how much in a single day?',
    promptAr: 'يمكن لبعض أنواع الخيزران أن تنمو كم في يوم واحد؟',
    answer: 'Nearly a metre',
    answerAr: 'قرابة المتر',
    acceptedVariants: ['a metre', 'almost a meter', '91cm', 'about 1 metre'],
    acceptedVariantsAr: ['متر تقريبا', 'حوالي متر'],
    source: 'Guinness World Records — fastest growing plant',
  },
  {
    category: 'Nature',
    difficulty: 'hard',
    prompt: 'There are more trees on Earth than there are these in the Milky Way. More than what?',
    promptAr: 'عدد الأشجار على الأرض يفوق عدد هذه في مجرة درب التبانة. يفوق عدد ماذا؟',
    answer: 'Stars',
    answerAr: 'النجوم',
    acceptedVariants: ['star', 'the stars'],
    acceptedVariantsAr: ['نجوم', 'نجمة'],
    source: 'Crowther et al., Nature, 2015',
  },
  {
    category: 'Nature',
    difficulty: 'medium',
    prompt: 'By the meteorological definition, the largest one on Earth is Antarctica. The largest what?',
    promptAr: 'وفق التعريف المناخي، أكبر واحدة على الأرض هي القارة القطبية الجنوبية. أكبر ماذا؟',
    answer: 'Desert',
    answerAr: 'صحراء',
    acceptedVariants: ['the desert', 'cold desert'],
    acceptedVariantsAr: ['الصحراء', 'صحراء باردة'],
    source: 'British Antarctic Survey',
  },
  {
    category: 'Nature',
    difficulty: 'hard',
    prompt: 'The largest living organism on Earth, covering several square kilometres in Oregon, is which kind of thing?',
    promptAr: 'أكبر كائن حي على الأرض، ويغطي عدة كيلومترات مربعة في ولاية أوريغون، هو أي نوع من الكائنات؟',
    answer: 'A fungus',
    answerAr: 'فطر',
    acceptedVariants: ['fungus', 'a mushroom', 'honey fungus'],
    acceptedVariantsAr: ['فطريات', 'الفطر'],
    source: 'US Forest Service — Malheur National Forest, Armillaria ostoyae',
  },

  // --- Strange facts ---
  {
    category: 'Strange facts',
    difficulty: 'hard',
    prompt: "Scotland's official national animal is which creature?",
    promptAr: 'الحيوان الوطني الرسمي لاسكتلندا هو أي مخلوق؟',
    answer: 'The unicorn',
    answerAr: 'وحيد القرن الأسطوري',
    acceptedVariants: ['unicorn', 'a unicorn'],
    acceptedVariantsAr: ['اليونيكورن', 'الحصان وحيد القرن'],
    source: 'National Records of Scotland; Royal Arms of Scotland',
  },
  {
    category: 'Strange facts',
    difficulty: 'hard',
    prompt: 'There are more possible games of chess than there are these in the observable universe. Than what?',
    promptAr: 'عدد مباريات الشطرنج الممكنة يفوق عدد هذه في الكون المرئي. يفوق ماذا؟',
    answer: 'Atoms',
    answerAr: 'الذرات',
    acceptedVariants: ['atom', 'the atoms'],
    acceptedVariantsAr: ['ذرات', 'ذرة'],
    source: 'Claude Shannon, 1950 — the Shannon number',
  },
  {
    category: 'Strange facts',
    difficulty: 'hard',
    prompt: 'Fredric Baur designed the Pringles can, and at his request his ashes were buried in what?',
    promptAr: 'صمم فريدريك باور علبة برينجلز، وبناءً على طلبه دُفن رماده في ماذا؟',
    answer: 'A Pringles can',
    answerAr: 'علبة برينجلز',
    acceptedVariants: ['pringles can', 'a pringles tube', 'the can'],
    acceptedVariantsAr: ['علبة شيبس', 'أنبوب برينجلز'],
    source: 'Cincinnati Enquirer obituary, 2008',
  },
  {
    category: 'Strange facts',
    difficulty: 'medium',
    prompt: 'A day on Venus is longer than what?',
    promptAr: 'اليوم على كوكب الزهرة أطول من ماذا؟',
    answer: 'A year on Venus',
    answerAr: 'السنة على الزهرة',
    acceptedVariants: ['a venus year', 'its year', 'the year on venus'],
    acceptedVariantsAr: ['سنة الزهرة', 'سنته'],
    source: 'NASA — Venus fact sheet',
  },

  // --- Saudi/GCC facts ---
  {
    category: 'Saudi/GCC facts',
    difficulty: 'easy',
    prompt: 'In which year was the Kingdom of Saudi Arabia unified and named?',
    promptAr: 'في أي عام تم توحيد المملكة العربية السعودية وتسميتها بهذا الاسم؟',
    answer: '1932',
    answerAr: '١٩٣٢',
    acceptedVariants: ['1932', 'nineteen thirty two'],
    acceptedVariantsAr: ['1932', '١٣٥١'],
    source: 'Royal Decree of 23 September 1932',
  },
  {
    category: 'Saudi/GCC facts',
    difficulty: 'medium',
    prompt: 'The Burj Khalifa in Dubai stands how tall?',
    promptAr: 'كم يبلغ ارتفاع برج خليفة في دبي؟',
    answer: '828 metres',
    answerAr: '٨٢٨ مترًا',
    acceptedVariants: ['828', '828m', '828 meters'],
    acceptedVariantsAr: ['828', '٨٢٨', '828 متر'],
    source: 'Council on Tall Buildings and Urban Habitat',
  },
  {
    category: 'Saudi/GCC facts',
    difficulty: 'medium',
    prompt: 'The King Fahd Causeway links Saudi Arabia to which country?',
    promptAr: 'يربط جسر الملك فهد المملكة العربية السعودية بأي دولة؟',
    answer: 'Bahrain',
    answerAr: 'البحرين',
    acceptedVariantsAr: ['مملكة البحرين'],
    source: 'King Fahd Causeway Authority',
  },
  {
    category: 'Saudi/GCC facts',
    difficulty: 'hard',
    prompt: 'The Nabataean city carved into rock in AlUla, and Saudi Arabia’s first UNESCO World Heritage Site, is called what?',
    promptAr: 'المدينة النبطية المنحوتة في الصخر بالعلا، وأول موقع سعودي على قائمة التراث العالمي لليونسكو، تُسمى ماذا؟',
    answer: 'Hegra',
    answerAr: 'الحِجر',
    acceptedVariants: ['madain salih', "mada'in saleh", 'hegra madain salih'],
    acceptedVariantsAr: ['مدائن صالح', 'الحجر'],
    source: 'UNESCO World Heritage List, inscribed 2008',
  },
  {
    category: 'Saudi/GCC facts',
    difficulty: 'hard',
    prompt: 'The vast sand sea covering much of southern Saudi Arabia is known in English as what?',
    promptAr: 'البحر الرملي الشاسع الذي يغطي جنوب السعودية يُعرف بأي اسم؟',
    answer: 'The Empty Quarter',
    answerAr: 'الربع الخالي',
    acceptedVariants: ['empty quarter', 'rub al khali', "rub' al-khali"],
    acceptedVariantsAr: ['الربع الخالي', 'ربع خالي'],
    source: 'Britannica — Rub al-Khali',
  },

  // --- World facts ---
  {
    category: 'World facts',
    difficulty: 'medium',
    prompt: 'Which country holds the record for the most official languages, at sixteen?',
    promptAr: 'أي دولة تحمل الرقم القياسي في عدد اللغات الرسمية، بستة عشر لغة؟',
    answer: 'Zimbabwe',
    answerAr: 'زيمبابوي',
    acceptedVariantsAr: ['زمبابوي'],
    source: 'Constitution of Zimbabwe, 2013, Section 6',
  },
  {
    category: 'World facts',
    difficulty: 'medium',
    prompt: 'Vatican City, the smallest country in the world, has a population of roughly how many?',
    promptAr: 'دولة الفاتيكان، أصغر دولة في العالم، يبلغ عدد سكانها نحو كم نسمة؟',
    answer: 'About 800',
    answerAr: 'نحو ٨٠٠',
    acceptedVariants: ['800', 'eight hundred', '~800'],
    acceptedVariantsAr: ['800', '٨٠٠', 'ثمانمئة'],
    source: 'Holy See Press Office',
  },
  {
    category: 'World facts',
    difficulty: 'hard',
    prompt: 'Which country is the only one to be a continent, a country and an island all at once?',
    promptAr: 'أي دولة هي الوحيدة التي تُعد قارة ودولة وجزيرة في آن واحد؟',
    answer: 'Australia',
    answerAr: 'أستراليا',
    acceptedVariantsAr: ['استراليا'],
    source: 'Geoscience Australia',
  },
];
