name: Fly Add Certificate

on:
  workflow_dispatch:
    inputs:
      hostname:
        description: "Hostname to add a certificate for"
        required: true
        default: "bahjah.com"

jobs:
  add-cert:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      APP: bahjah
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Add certificate
        run: flyctl certs add "${{ github.event.inputs.hostname }}" -a "$APP"

      - name: Show certificate status
        run: flyctl certs show "${{ github.event.inputs.hostname }}" -a "$APP"
